#!/bin/bash

cd ${0%/*} || exit 1    # run from this directory

source "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"/etc/bashrc

rmdepall
wcleanLnIncludeAll
wcleanAll

( cd metis && ./AllClean )
