#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

set -x

wmake plasmaSimFoam
wmake plasmaMultiRegionFoam
wmake somaFoam
wmake all mesh
wmake all miscellaneous
wmake all parallelProcessing
wmake all postProcessing
wmake all preProcessing

# ----------------------------------------------------------------- end-of-file
