#!/bin/bash

for dir in packages rpmBuild/BUILD rpmBuild/BUILDROOT rpmBuild/rpmDB rpmBuild/RPMS rpmBuild/SRPMS rpmBuild/TGZS rpmBuild/tmp
do
    echo "Removing $dir/"
    [ -d $dir ] && rm -rf $dir
done
