#!/bin/bash

cd ${0%/*} || exit 1

. makeThirdPartyFunctionsForRPM
#------------------------------------------------------------------------------

[ ! -z "$WM_THIRD_PARTY_USE_CMAKE_322" ] && {
    echo "Building cmake 3.2.2"
    ( rpm_make -p cmake-3.2.2 -s cmake-3.2.2.spec -u http://www.cmake.org/files/v3.2/cmake-3.2.2.tar.gz        )
}

[ ! -z "$WM_THIRD_PARTY_USE_METIS_510" ] && {
echo "Building metis 5.1.0"
( rpm_make -p metis-5.1.0 -s metis-5.1.0.spec -u http://downloads.sourceforge.net/project/foam-extend/ThirdParty/metis-5.1.0.tar.gz )
}
