#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

# Make meshMotion solvers
wmake libso solidBodyMotion
wmake libso fvMotionSolver
wmake libso RBFMotionSolver

# ----------------------------------------------------------------- end-of-file
