#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wmakeLnInclude decompositionMethods

wmake libso decompositionMethods
wmake libso metisDecomp


# ----------------------------------------------------------------- end-of-file
