#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -f constant/polyMesh/boundary
rm -rf constant/polyMesh/[c-z]*

nDielecReg=$@

for ((i = 1 ; i <= nDielecReg ; i++))
do
	rm -f constant/dielectric_$i/polyMesh/boundary
	rm -rf constant/dielectric_$i/polyMesh/[c-z]*
	rm -f dielectric_$i.setSet
	rm -f plasma_$i.setSet
done

rm -f reconstructParScript
rm -f decomposeParScript
rm -f $(echo "${PWD##*/}").foam
rm -rf *e-*
rm -rf processor*
