#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

set -x

wmakePrintBuild -check || /bin/rm -f foam/Make/$WM_OPTIONS/global.? 2>/dev/null

wmakeLnInclude foam
wmakeLnInclude meshTools
wmakeLnInclude OSspecific/$WM_OSTYPE

wmake libo  OSspecific/$WM_OSTYPE
wmake libso foam

decompositionMethods/AllwmakeLnInclude
decompositionMethods/Allwmake

wmake libso lagrangian/basic

wmake libso edgeMesh
wmake libso surfMesh
wmake libso meshTools

wmake libso finiteVolume
wmake libso finiteArea

wmake libso lduSolvers

dynamicMesh/AllwmakeLnInclude
dynamicMesh/Allwmake

wmake libso coupledMatrix
wmake libso sampling

wmake libso ODE

mesh/Allwmake

thermophysicalModels/Allwmake

postProcessing/Allwmake
conversion/Allwmake
wmake libso errorEstimation
wmake libso equationReader

plasmaCookBook/Allwmake
# ----------------------------------------------------------------- end-of-file
